### ISSUE TITLE
"No Module named 'binance_ap'"

### ISSUE THREAD

**Issue by dlasher** [dgokcin/binance-triangle-arbitrage#1]
root@box:# docker run -v "$(pwd)"/primary.txt:/app/primary.txt -e PUBLIC_KEY=KEY -e SECRET_KEY=KEY denizgokcin/binance-triangle-arbitrage:latest

Traceback (most recent call last):
  File "./main.py", line 7, in <module>
    import binance_api as api
ModuleNotFoundError: No module named 'binance_api'

**Comment by dgokcin** [comment]
@dlasher Could you please try again? I think I accidentally uploaded an incomplete version of the docker container to DockerHub and tagged it as latest. I just pushed again.

**Comment by dlasher** [comment]
# docker pull denizgokcin/binance-triangle-arbitrage:latest

Runs now, but runs for about 20 lines then quits?

No triangles found, trying again!
Downloaded in: 0.3246s
Computed in: 0.0907s
BTC->BNB->TOMO->BTC         0.0269% <- profit!
     BNB  / BTC :      498.92730629
     TOMO / BNB :       22.75830678
     BTC  / TOMO:        0.00008751


Is there a way to "keep" it running? reporting/etc?

**Comment by dgokcin** [comment]
@dlasher you can call the main() function again like in the following snippet in main.py line 78.
but then you either have to run main.py from your local machine or if you want to use docker, build your own container, since this is not the current app deployed to dockerhub.

```python
    if triangles:
        for triangle in sorted(triangles, key=itemgetter('profit'), reverse=True):
            describe_triangle(prices, triangle)
        main()
    else:
        print("No triangles found, trying again!")
        main()
```
